spring:
  application:
    name: eureka-service

server:
  port: 8302

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    db-service:
      path: /catologue-service/**
      url: http://localhost:8300
    stock-service:
      path: /pricing-service/**
      url: http://localhost:8301